# Inserts a blank line between shell prompts
add_newline = true

command_timeout = 2000

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[âœ](bold green)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'
error_symbol = '[âœ—](bold red)'

[cmd_duration]
disabled = true
style = 'dimmed gray'

[directory]
style = 'bold blue'
# truncation_length = 3
# truncate_to_repo = false
truncation_symbol = 'ï» '

[git_metrics]
disabled = false

[hostname]
ssh_only = true
# aliases = { "lm21" = "ğŸ§" }

# [line_break]
# disabled = true

[golang]
symbol = "î˜§ "

[python]
symbol = "îˆµ "

[nodejs]
symbol = "îœ˜ "

[dart]
symbol = "î˜ "

[lua]
symbol = "î˜  "

[rust]
symbol = "î¨ "

[c]
symbol = "î˜ "

[docker_context]
symbol = "ïŒˆ "

[zig]
symbol = "îš©  "
detect_files = ["build.zig", "build.zig.zon"]
